name: Character
version: 0.5
api-version: 1.16
author: TomDalton
main: de.TomDalton.Character.Main
description: Charakter-Erstellung
depend: [DLT_API, Towny, Vault]

commands:
   ch:
      description: Hilfeseite aufrufen
      usage: /ch help
   char:
      description: Charakter eines Spielers aufrufen
      usage: /char *Spielername/RP-Name*